# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dbd465a1d3440195078f629459cdd54040eb97968b28edc0338b3437e4bc56f03ee500bf9b1d1b80999650a56b331484d7216bc13378fe7dadcb5f4867a5e45

test:
  secret_key_base: 1b5e1b3ac37fe60d2ad7150e291f493699a833a53271cc26555175751b0122895010972cb90cd3dc73183c15f796caba583b1cf248b65719c2d5cb87234bb8c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
